---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
    config:
      extensions:
      - .es6
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.py"
exclude_paths:
- "tests/"
- "static/"
- "pytz/"